//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookHotelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING_DETAILS
    {
        public string EMAIL { get; set; }
        public int IDROOM { get; set; }
        public System.DateTime ROOM_TIME { get; set; }
        public System.DateTime PAYMENT_TIME { get; set; }
        public Nullable<int> AMOUNT_OF_PEOPLE { get; set; }
        public Nullable<int> AMOUNT_OF_ROOM { get; set; }
    
        public virtual Account ACCOUNT { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
